user_states = {}

STATE_WAITING_DESCRIPTION = "WAITING_DESCRIPTION"
STATE_WAITING_TITLE = "WAITING_TITLE"
STATE_WAITING_ASSIGNEE = "WAITING_ASSIGNEE"
STATE_WAITING_DUE_DATE = "waiting_due_date"
STATE_WAITING_STATUS = "WAITING_STATUS"
STATE_WAITING_CHOISE = "WAITING_CHOISE"
STATE_DELETE_TASK = "DELETE_TASK_ASSIGNEE"
STATE_WAITING_TASK_NUMBER = "DELETE_TASK_NUMBER"
STATE_SHOW_TASK = "SHOW_TASK"
STATE_WAITING_ASSIGNEE_FOR_SHOWING_TASKS = "SHOW_TASK_ASSIGNEE"
STATE_WAITING_ASSIGNEE_FOR_DELETE = "DELETE_TASK_ASSIGNEE"
STATE_WAITING_TASK_NUMBER_FOR_DELETE = "DELETE_TASK_NUMBER"
STATES = {
    'WAITING_TITLE': 1,
    'WAITING_DESCRIPTION': 2,
    'WAITING_ASSIGNEE': 3,
    'WAITING_DUE_DATE': 4,
    'WAITING_REMINDER_TYPE': 5,
    'WAITING_DAILY_TIME': 6

}

DB_CONFIG = {
    "dbname": "",
    "user": "",
    "password": "",
    "host": "",
    "port": 

}
